# Generated by Django 2.2 on 2019-04-08 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='stock_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_id', models.IntegerField()),
                ('stock_name', models.CharField(max_length=20)),
                ('theme_id', models.CharField(max_length=20)),
                ('theme_name', models.CharField(max_length=20)),
                ('description', models.TextField()),
            ],
            options={
                'ordering': ('stock_id',),
            },
        ),
    ]
